/**
 * Woden
 * Specification for Woden REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Body2 model module.
* @module model/Body2
* @version 1.0.0
*/
export default class Body2 {
    /**
    * Constructs a new <code>Body2</code>.
    * @alias module:model/Body2
    * @class
    * @param login {String} 
    * @param password {String} 
    * @param certificate {Blob} The certificate to upload.
    * @param privateKey {Blob} The private key to upload.
    */

    constructor(login, password, certificate, privateKey) {
        
        
        this['login'] = login;
        this['password'] = password;
        this['certificate'] = certificate;
        this['privateKey'] = privateKey;
        
    }

    /**
    * Constructs a <code>Body2</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Body2} obj Optional instance to populate.
    * @return {module:model/Body2} The populated <code>Body2</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Body2();
                        
            
            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('certificate')) {
                obj['certificate'] = ApiClient.convertToType(data['certificate'], 'Blob');
            }
            if (data.hasOwnProperty('privateKey')) {
                obj['privateKey'] = ApiClient.convertToType(data['privateKey'], 'Blob');
            }
        }
        return obj;
    }

    /**
    * @member {String} login
    */
    login = undefined;
    /**
    * @member {String} password
    */
    password = undefined;
    /**
    * The certificate to upload.
    * @member {Blob} certificate
    */
    certificate = undefined;
    /**
    * The private key to upload.
    * @member {Blob} privateKey
    */
    privateKey = undefined;




}
