/*
 * Woden
 * Specification for Woden REST API
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Woden) {
      root.Woden = {};
    }
    root.Woden.UploadFile = factory(root.Woden.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The UploadFile model module.
   * @module model/UploadFile
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UploadFile</code>.
   * @alias module:model/UploadFile
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UploadFile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UploadFile} obj Optional instance to populate.
   * @return {module:model/UploadFile} The populated <code>UploadFile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('parentFolder'))
        obj.parentFolder = ApiClient.convertToType(data['parentFolder'], 'String');
      if (data.hasOwnProperty('file'))
        obj.file = ApiClient.convertToType(data['file'], Object);
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} parentFolder
   */
  exports.prototype.parentFolder = undefined;

  /**
   * @member {Object} file
   */
  exports.prototype.file = undefined;

  return exports;

}));
