// /*
//  * Woden
//  * Specification for Woden REST API
//  *
//  * OpenAPI spec version: 1.0.0
//  *
//  * NOTE: This class is auto generated by the swagger code generator program.
//  * https://github.com/swagger-api/swagger-codegen.git
//  *
//  * Swagger Codegen version: 2.4.13
//  *
//  * Do not edit the class manually.
//  *
//  */

// (function(root, factory) {
//   if (typeof define === 'function' && define.amd) {
//     // AMD.
//     define(['expect.js', '../../src/index'], factory);
//   } else if (typeof module === 'object' && module.exports) {
//     // CommonJS-like environments that support module.exports, like Node.
//     factory(require('expect.js'), require('../../src/index'));
//   } else {
//     // Browser globals (root is window)
//     factory(root.expect, root.Woden);
//   }
// }(this, function(expect, Woden) {
//   'use strict';

//   var instance;

//   describe('(package)', function() {
//     describe('UploadFile', function() {
//       beforeEach(function() {
// //         instance = new Woden.UploadFile();
//       });

//       it('should create an instance of UploadFile', function() {
//         // TODO: update the code to test UploadFile
//         expect(instance).to.be.a(Woden.UploadFile);
//       });

//       it('should have the property name (base name: "name")', function() {
//         // TODO: update the code to test the property name
//         expect(instance).to.have.property('name');
//         // expect(instance.name).to.be(expectedValueLiteral);
//       });

//       it('should have the property parentFolder (base name: "parentFolder")', function() {
//         // TODO: update the code to test the property parentFolder
//         expect(instance).to.have.property('parentFolder');
//         // expect(instance.parentFolder).to.be(expectedValueLiteral);
//       });

//       it('should have the property file (base name: "file")', function() {
//         // TODO: update the code to test the property file
//         expect(instance).to.have.property('file');
//         // expect(instance.file).to.be(expectedValueLiteral);
//       });

//     });
//   });

// }));
